 services:
   api-students:
     build: ./api-students
     ports:
       - 8000:8000
   websimple:
     build: ./websimple
     ports:
       - 8080:80
   websplantilla:
     build: ./webplantilla
     ports:
       - 8081:80
